### ISSUE TITLE
Insufficient Documentation

### ISSUE THREAD

**Issue by bhuvana-sankaralingam** [OpenCerts/opencerts-functions#42]
Able to call the Verify API, but there is not enough information on how to interpret the response:
1. Which fields in the response are used to indicate if the OpenCert is verified? Is it possible to provide API specification?
2. How to check if the OpenCert issuer is registered under SSG?

**Comment by Nebulis** [comment]
I'm currently working on that it should be ready soon and better explained. In the meanwhile:
1. There is a summary object returned
```
"summary": {
        "all": true,
        "documentStatus": true,
        "documentIntegrity": true,
        "issuerIdentity": true
    },
```
Probably what you are looking for is `summary.all`

2. It's already there but it will be updated once https://github.com/OpenCerts/verify is released. To get the information, you can look in data array for the entry with name "OpencertsRegistryVerifier". If the value is VALID then the issuer is in the registry.

**Comment by Nebulis** [comment]
Added some documentation, let me know if you would need more details

https://github.com/OpenCerts/opencerts-functions
