### ISSUE TITLE
How to user this api?

### ISSUE THREAD

**Issue by Rohanashik** [OpenCerts/opencerts-functions#55]
```
curl --header "Content-Type: application/json" \
  --request POST \
  --data '{"document":"<OA_DOCUMENT_HERE>"}' \
  https://api.opencerts.io/verify
```

In here what is OA_DOCUMENT_HERE ?

How publish file in opencert and verify?

Is there any video demo for this api

The documentation is too broad to understand

**Comment by rjchow** [comment]
1) OA_DOCUMENT_HERE is simply the contents of a signed tradetrust file
2) https://docs.tradetrust.io/quickstart
3) no

**Comment by Rohanashik** [comment]
How to sign tradetrust file via api?
For example, I want to sign a PDF file.

How to do that via api?

**Comment by rjchow** [comment]
that is not possible at this point in time, please refer to the documentation I linked above

**Comment by Rohanashik** [comment]
Ohhh thats, okay thanks for replying fast!
