### ISSUE TITLE
dev api

### ISSUE THREAD

**Issue by asepem7** [OpenCerts/opencerts-functions#59]
is the API url for test development available ? 
like dev.opencerts.io, so I can verify my document using dev mode?

**Comment by Nebulis** [comment]
https://api-ropsten.opencerts.io/verify

We dont guarantee SLA or consistency accross the time (i.e. we may change the response shape without notice even if it didnt happen for a while)

**Comment by asepem7** [comment]
ok no problem, thank you very much

**Comment by asepem7** [comment]
"summary": {
    "all": false,
    "documentStatus": false,
    "documentIntegrity": true,
    "issuerIdentity": true
  },

I've verify my document to verify with API. based on response above what mean documentStatus? how to make documentStatus to be true ?

Thanks

**Comment by Nebulis** [comment]
Document status is about issuance and revocation
- either you didn't issue the document
- either you revoked the document
- either you use the wrong network
(Or all of them)

You will probably find more details in the huge object coming with (search for error or invalid)

**Comment by asepem7** [comment]
I use ropsten network and for this document i've issued to ropsten.
and if I check the json file in dev.opencerts.io is valid

**Comment by Nebulis** [comment]
Document?

**Comment by asepem7** [comment]
i mean the JSON File

**Comment by Nebulis** [comment]
I meant send me the document =)

**Comment by asepem7** [comment]
[docsample.zip](https://github.com/OpenCerts/opencerts-functions/files/4537705/docsample.zip)

**Comment by Nebulis** [comment]
![image](https://user-images.githubusercontent.com/503185/80338615-579f9b00-888f-11ea-8c98-41ac0cef8e3f.png)

it works for me :thinking:

**Comment by asepem7** [comment]
hmmm weird, I will try it again later.

I just want to know about this :

Document status is about issuance and revocation

either you didn't issue the document
either you revoked the document
either you use the wrong network
(Or all of them)
You will probably find more details in the huge object coming with (search for error or invalid)

so if my document has been issued the documentStatus will be true right ?

thank you very much.

**Comment by Nebulis** [comment]
Yes it must be true if the document has been issued (and also if it works on dev.opencerts.io.

If you still have the problem check the data object (you can eventually add the content here)

Check this out => https://github.com/Open-Attestation/adr/blob/master/verifier.md

**Comment by asepem7** [comment]
Thanks
