### ISSUE TITLE
Verify API - Internal Server Error

### ISSUE THREAD

**Issue by lyn-ecq** [OpenCerts/opencerts-functions#88]
Hi,

We are trying to call the verify API using Postman but is getting Internal Server Error.
Attached screenshot:

![Verify_API](https://user-images.githubusercontent.com/94041448/141076411-c4c3375d-72f7-41fe-a85d-0ac99e20b3ad.png)

Can this API still be used?

**Comment by Nebulis** [comment]
Can you share the content of the request?

**Comment by lyn-ecq** [comment]
Hi, 

Thank you for the prompt response. 
We managed to find out the root cause and was able to resolve it.
