### ISSUE TITLE
Invalid Document Status

### ISSUE THREAD

**Issue by lyn-ecq** [OpenCerts/opencerts-functions#91]
I have an opencert document that shows that it is valid on opencerts.io.
However, when verifying the document via https://api.opencerts.io/verify, it is showing:

```
"summary": {
        "all": false,
        "documentStatus": false,
        "documentIntegrity": true,
        "issuerIdentity": true
    }
...
...
...
{
            "status": "SKIPPED",
            "type": "DOCUMENT_STATUS",
            "name": "OpenAttestationEthereumTokenRegistryStatus",
            "reason": {
                "code": 4,
                "codeString": "SKIPPED",
                "message": "Document issuers doesn't have \"tokenRegistry\" property or TOKEN_REGISTRY method"
            }
        },
        {
            "status": "SKIPPED",
            "type": "DOCUMENT_STATUS",
            "name": "OpenAttestationEthereumDocumentStoreStatus",
            "reason": {
                "code": 4,
                "codeString": "SKIPPED",
                "message": "Document issuers doesn't have \"documentStore\" or \"certificateStore\" property or DOCUMENT_STORE method"
            }
        },
        {
            "name": "OpenAttestationDidSignedDocumentStatus",
            "type": "DOCUMENT_STATUS",
            "data": {
                "issuedOnAll": true,
                "revokedOnAny": true,
                "details": {
                    "issuance": [
                        {
                            "issued": true,
                            "did": "did:ethr:0x9690379d9c4e81515c83f6d4c1d5e248144521bd"
                        }
                    ]
                }
            },
            "status": "INVALID"
        }
```

Any idea what is the issue?

**Comment by HJunyuan** [comment]
May I suggest you try to verify or diagnose the document in question using the online toolkit:
- https://toolkit.openattestation.com/verify
- https://toolkit.openattestation.com/diagnose

**Comment by lyn-ecq** [comment]
Hi,

For https://toolkit.openattestation.com/verify
it is showing this for Mainnet:

![image](https://user-images.githubusercontent.com/94041448/162114693-42ae89d7-9fb3-4d33-99bb-2311556229d5.png)

But for Ropsten:
![image](https://user-images.githubusercontent.com/94041448/162114770-9cadf77f-7052-4a30-91c3-f022831cdce2.png)
`{
    "name": "OpenAttestationDidSignedDocumentStatus",
    "type": "DOCUMENT_STATUS",
    "data": {
      "issuedOnAll": true,
      "revokedOnAny": true,
      "details": {
        "issuance": [
          {
            "issued": true,
            "did": "did:ethr:0x9690379d9c4e81515c83f6d4c1d5e248144521bd"
          }
        ],
        "revocation": [
          {
            "revoked": true,
            "address": "0x0036097d5c34afddf085e6bbfdb2eee255fce3b0",
            "reason": {
              "message": "Contract is not found",
              "code": 5,
              "codeString": "DOCUMENT_REVOKED"
            }
          }
        ]
      }
    },
    "status": "INVALID",
    "reason": {
      "message": "Contract is not found",
      "code": 5,
      "codeString": "DOCUMENT_REVOKED"
    }`


For https://toolkit.openattestation.com/diagnose
It is showing
![image](https://user-images.githubusercontent.com/94041448/162114898-b547215b-5fb8-49ec-93c9-e9acf3464375.png)


Any idea why it is showing DOCUMENT_REVOKED in the 1st URL but is showing document is valid in opencerts.io?
![image](https://user-images.githubusercontent.com/94041448/162115024-c8b41171-1e44-4d7b-842d-de50f3882b8f.png)

**Comment by HJunyuan** [comment]
This is the correct behaviour for the Ropsten screenshot.

The document you are trying to verify is issued to a document store address on the Mainnet (production). That is, the same document store address for Mainnet is not present on the Ropsten network which is why you see the message: `Contract is not found`

**Comment by lyn-ecq** [comment]
Okay. Does this mean that the document store is also not present on https://api.opencerts.io/verify ?

**Comment by HJunyuan** [comment]
Could you provide the full response coming from `https://api.opencerts.io/verify`?

**Comment by lyn-ecq** [comment]
Here it is
{
    "summary": {
        "all": false,
        "documentStatus": false,
        "documentIntegrity": true,
        "issuerIdentity": true
    },
    "data": [
        {
            "type": "DOCUMENT_INTEGRITY",
            "name": "OpenAttestationHash",
            "data": true,
            "status": "VALID"
        },
        {
            "status": "SKIPPED",
            "type": "DOCUMENT_STATUS",
            "name": "OpenAttestationEthereumTokenRegistryStatus",
            "reason": {
                "code": 4,
                "codeString": "SKIPPED",
                "message": "Document issuers doesn't have \"tokenRegistry\" property or TOKEN_REGISTRY method"
            }
        },
        {
            "status": "SKIPPED",
            "type": "DOCUMENT_STATUS",
            "name": "OpenAttestationEthereumDocumentStoreStatus",
            "reason": {
                "code": 4,
                "codeString": "SKIPPED",
                "message": "Document issuers doesn't have \"documentStore\" or \"certificateStore\" property or DOCUMENT_STORE method"
            }
        },
        {
            "name": "OpenAttestationDidSignedDocumentStatus",
            "type": "DOCUMENT_STATUS",
            "data": {
                "issuedOnAll": true,
                "revokedOnAny": true,
                "details": {
                    "issuance": [
                        {
                            "issued": true,
                            "did": "did:ethr:0x9690379d9c4e81515c83f6d4c1d5e248144521bd"
                        }
                    ]
                }
            },
            "status": "INVALID"
        },
        {
            "status": "SKIPPED",
            "type": "ISSUER_IDENTITY",
            "name": "OpenAttestationDnsTxtIdentityProof",
            "reason": {
                "code": 2,
                "codeString": "SKIPPED",
                "message": "Document issuers doesn't have \"documentStore\" / \"tokenRegistry\" property or doesn't use DNS-TXT type"
            }
        },
        {
            "name": "OpenAttestationDnsDidIdentityProof",
            "type": "ISSUER_IDENTITY",
            "data": [
                {
                    "location": "niec.edu.sg",
                    "key": "did:ethr:0x9690379d9c4e81515c83f6d4c1d5e248144521bd#controller",
                    "status": "VALID"
                }
            ],
            "status": "VALID"
        },
        {
            "status": "SKIPPED",
            "type": "ISSUER_IDENTITY",
            "name": "OpencertsRegistryVerifier",
            "reason": {
                "code": 1,
                "codeString": "SKIPPED",
                "message": "Document issuers doesn't have \"documentStore\" or \"certificateStore\" property or DOCUMENT_STORE method"
            }
        }
    ]
}

**Comment by HJunyuan** [comment]
Could you double-check or show us the `issuers` field of your document? It should look something like:

```json
{
  // ...
  "issuers": [
    {
      "name": "SAMPLE ISSUER (DO NOT VERIFY)",
      "id": "did:ethr:0xE39479928Cc4EfFE50774488780B9f616bd4B830",
      "revocation": {
        "type": "NONE"
      },
      "identityProof": {
        "type": "DNS-DID",
        "location": "donotverify.testing.verify.gov.sg",
        "key": "did:ethr:0xE39479928Cc4EfFE50774488780B9f616bd4B830#controller"
      }
    }
  ]
}
```

**Comment by lyn-ecq** [comment]
```
"issuers": [
		  {
			"id": "ceb670c4-4b05-436b-95c0-3cbbd0078f49:string:did:ethr:0x9690379d9c4e81515c83f6d4c1d5e248144521bd",
			"name": "f92e814d-c497-420e-a227-9e45fdb38417:string:National Institute of Early Childhood Development",
			"revocation": {
			  "type": "af52c98b-6cf0-4d49-a40b-dea3d07087e3:string:REVOCATION_STORE",
			  "location": "a0c9cd9a-9eb2-44be-8c62-8393e07d71a0:string:0x0036097d5c34afddf085e6bbfdb2eee255fce3b0"
			},
			"identityProof": {
			  "type": "77cf69d1-6ef4-4f33-83a1-acaf997f71c7:string:DNS-DID",
			  "key": "adb704db-c2d5-4f1d-aba5-ae151ac1a6c2:string:did:ethr:0x9690379d9c4e81515c83f6d4c1d5e248144521bd#controller",
			  "location": "54426b70-83d1-49b7-b3a3-7e5ba803923e:string:niec.edu.sg"
			}
		  }
		]
```

**Comment by simboonlong** [comment]
is ok if you share us your document json file? will have a look

**Comment by lyn-ecq** [comment]
The document contains sensitive data, so I cannot share it here.

**Comment by HJunyuan** [comment]
@lyn-ecq We've deployed some changes. Please try again.
